services:
  frontend:
    build:
      context: .
      dockerfile: frontend-prod.dockerfile
      args:
        NODE_ENV: production
    container_name: falcontouch-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
